#ifndef DM_CONNECTIONSETTINGS_H
#define DM_CONNECTIONSETTINGS_H

#include "lwip/ip_addr.h"
#include "Sensify-config.h"

class ConnectionSettings
{
    public:
        struct StaticIP
        {
            ip_addr_t ip;
            ip_addr_t subnet;
            ip_addr_t gateway;
            ip_addr_t dns;
        };

        struct NTPSettings
        {
            char ntpFQDN[256];
            ip_addr_t fallbackIP;
        };

        struct WiFiSettings
        {
            char ssid[33]; //32 max?
            char pass[64]; //63 max?
        };

        struct MQTTSettings
        {
            char serverFQDN[256];
            ip_addr_t fallbackIP;
            u16_t port;
        };

        struct NetworkProfile 
        {
            WiFiSettings wifi;
            MQTTSettings mqtt;
            NTPSettings ntp;
            bool useDHCP;                                    
            StaticIP staticIP;            
        };

        struct ConnectionData
        {
            char connectionString[512];
            NetworkProfile networkProfiles[SENSIFY_NUMBER_OF_WIFI_PROFILES];
        };
};

/*
Memory allocation of ConnectionData (generated by Test.cpp)

====================[ ConnectionString Dimensions ]====================
DEBUG   [INFO]  SizeOf: 2444 bytes
DEBUG   [INFO]  connectionData->connectionString:      		 	        Start: 0        Size: 512       End: 512
DEBUG   [INFO]  connectionData->networkProfiles:      		 	        Start: 512      Size: 1932      End: 2444
DEBUG   [INFO]  connectionData->networkProfiles[0]:    			        Start: 512      Size: 644       End: 1156
DEBUG   [INFO]  connectionData->networkProfiles[0].wifi.ssid:       	Start: 512      Size: 33        End: 545
DEBUG   [INFO]  connectionData->networkProfiles[0].wifi.pass:       	Start: 545      Size: 64        End: 609
DEBUG   [INFO]  connectionData->networkProfiles[0].mqtt.serverFQDN:     Start: 612      Size: 256       End: 868
DEBUG   [INFO]  connectionData->networkProfiles[0].mqtt.fallbackIP:     Start: 868      Size: 4  	    End: 872
DEBUG   [INFO]  connectionData->networkProfiles[0].mqtt.port:   	    Start: 872      Size: 2  	    End: 874
DEBUG   [INFO]  connectionData->networkProfiles[0].ntp.ntpFQDN: 	    Start: 876      Size: 256       End: 1132
DEBUG   [INFO]  connectionData->networkProfiles[0].ntp.fallbackIP:      Start: 1132     Size: 4  	    End: 1136
DEBUG   [INFO]  connectionData->networkProfiles[0].useDHCP:     	    Start: 1136     Size: 1 	    End: 1137
DEBUG   [INFO]  connectionData->networkProfiles[0].staticIP.ip: 	    Start: 1140     Size: 4  	    End: 1144
DEBUG   [INFO]  connectionData->networkProfiles[0].staticIP.subnet:     Start: 1144     Size: 4  	    End: 1148
DEBUG   [INFO]  connectionData->networkProfiles[0].staticIP.gateway:    Start: 1148     Size: 4  	    End: 1152
DEBUG   [INFO]  connectionData->networkProfiles[0].staticIP.dns:        Start: 1152     Size: 4  	    End: 1156
DEBUG   [INFO]  connectionData->networkProfiles[1]:     		        Start: 1156     Size: 644       End: 1800
DEBUG   [INFO]  connectionData->networkProfiles[1].wifi.ssid:   	    Start: 1156     Size: 33        End: 1189
DEBUG   [INFO]  connectionData->networkProfiles[1].wifi.pass:   	    Start: 1189     Size: 64        End: 1253
DEBUG   [INFO]  connectionData->networkProfiles[1].mqtt.serverFQDN:     Start: 1256     Size: 256       End: 1512
DEBUG   [INFO]  connectionData->networkProfiles[1].mqtt.fallbackIP:     Start: 1512     Size: 4  	    End: 1516
DEBUG   [INFO]  connectionData->networkProfiles[1].mqtt.port:   	    Start: 1516     Size: 2  	    End: 1518
DEBUG   [INFO]  connectionData->networkProfiles[1].ntp.ntpFQDN: 	    Start: 1520     Size: 256       End: 1776
DEBUG   [INFO]  connectionData->networkProfiles[1].ntp.fallbackIP:      Start: 1776     Size: 4  	    End: 1780
DEBUG   [INFO]  connectionData->networkProfiles[1].useDHCP:     	    Start: 1780     Size: 1  	    End: 1781
DEBUG   [INFO]  connectionData->networkProfiles[1].staticIP.ip: 	    Start: 1784     Size: 4  	    End: 1788
DEBUG   [INFO]  connectionData->networkProfiles[1].staticIP.subnet:     Start: 1788     Size: 4  	    End: 1792
DEBUG   [INFO]  connectionData->networkProfiles[1].staticIP.gateway:    Start: 1792     Size: 4  	    End: 1796
DEBUG   [INFO]  connectionData->networkProfiles[1].staticIP.dns:        Start: 1796     Size: 4  	    End: 1800
DEBUG   [INFO]  connectionData->networkProfiles[2]:     		        Start: 1800     Size: 644       End: 2444
DEBUG   [INFO]  connectionData->networkProfiles[2].wifi.ssid:   	    Start: 1800     Size: 33        End: 1833
DEBUG   [INFO]  connectionData->networkProfiles[2].wifi.pass:   	    Start: 1833     Size: 64        End: 1897
DEBUG   [INFO]  connectionData->networkProfiles[2].mqtt.serverFQDN:     Start: 1900     Size: 256       End: 2156
DEBUG   [INFO]  connectionData->networkProfiles[2].mqtt.fallbackIP:     Start: 2156     Size: 4  	    End: 2160
DEBUG   [INFO]  connectionData->networkProfiles[2].mqtt.port:   	    Start: 2160     Size: 2  	    End: 2162
DEBUG   [INFO]  connectionData->networkProfiles[2].ntp.ntpFQDN: 	    Start: 2164     Size: 256       End: 2420
DEBUG   [INFO]  connectionData->networkProfiles[2].ntp.fallbackIP:      Start: 2420     Size: 4  	    End: 2424
DEBUG   [INFO]  connectionData->networkProfiles[2].useDHCP:     	    Start: 2424     Size: 1  	    End: 2425
DEBUG   [INFO]  connectionData->networkProfiles[2].staticIP.ip: 	    Start: 2428     Size: 4  	    End: 2432
DEBUG   [INFO]  connectionData->networkProfiles[2].staticIP.subnet:     Start: 2432     Size: 4  	    End: 2436
DEBUG   [INFO]  connectionData->networkProfiles[2].staticIP.gateway:    Start: 2436     Size: 4  	    End: 2440
DEBUG   [INFO]  connectionData->networkProfiles[2].staticIP.dns:        Start: 2440     Size: 4  	    End: 2444
*/

#endif