//Pins for PCB revision v1.4 (Identical to V1.3)

#ifndef SENSIFYBOARD_H
#define SENSIFYBOARD_H

#define SENSIFY_HARDWARE_REVISION v1.4

#define SENSIFY_IO_IN_1 16
#define SENSIFY_IO_IN_2 17
#define SENSIFY_IO_IN_3 18
#define SENSIFY_IO_IN_4 19
#define SENSIFY_IO_IN_5 20
#define SENSIFY_IO_IN_6 21
#define SENSIFY_IO_IN_7 22
#define SENSIFY_IO_IN_8 26
#define SENSIFY_IO_IN_9 7
#define SENSIFY_IO_IN_10 12

#define SENSIFY_STATUS_LED_1_GREEN 4
#define SENSIFY_STATUS_LED_2_ORANGE 6
#define SENSIFY_STATUS_LED_2_GREEN 5

#define SENSIFY_IO_MULTI_1_IN 7
#define SENSIFY_IO_MULTI_1_OUT 8
#define SENSIFY_IO_MULTI_2_IN 12
#define SENSIFY_IO_MULTI_2_OUT 11

#define SENSIFY_OUTIC_OUT_DEN 9
#define SENSIFY_OUTIC_OUT_DSEL 10
#define SENSIFY_OUTIC_INANALOG_IS_PIN 27
#define SENSIFY_OUTIC_INANALOG_IS_ADC 1
#define SENSIFY_OUTIC_IS_FAULT_CURRENT_THRESHOLD 0.006

#define SENSIFY_POWER_IN_24V_NOT_OK 13
#define SENSIFY_POWER_INANALOG_24V_PIN 28
#define SENSIFY_POWER_INANALOG_24V_ADC 2
#define SENSIFY_POWER_OUT_3V3_ENABLE 14
#define SENSIFY_POWER_IN_3V3_OK 15

#define SENSIFY_CONST_ANALOG_24V_MULTIPLIER 0.01047363281  // (3.3/4096)*13
#define SENSIFY_CONST_ANALOG_OUTIC_IS_MULTIPLER 1

#define SENSIFY_DS3231_I2C i2c1
#define SENSIFY_DS3231_SDA 2
#define SENSIFY_DS3231_SCL 3

static const int SENSIFY_IO_IN[] = {
    SENSIFY_IO_IN_1,
    SENSIFY_IO_IN_2,
    SENSIFY_IO_IN_3,
    SENSIFY_IO_IN_4,
    SENSIFY_IO_IN_5,
    SENSIFY_IO_IN_6,
    SENSIFY_IO_IN_7,
    SENSIFY_IO_IN_8,
    SENSIFY_IO_IN_9,
    SENSIFY_IO_IN_10
    };
#define SENSIFY_NUM_OF_INPUTS sizeof(SENSIFY_IO_IN)/sizeof(SENSIFY_IO_IN[0])

#endif