#define FIRMWARE_VERSION "1.2.1"
#define NTP_RETRIES 2
#define NTP_BLOCKING_THRESHOLD_MS 3000
#define MQTT_BLOCKING_THRESHOLD_MS 3000
#define MQTT_BASE64_BUFFER_SIZE 300
#define QOS 1
#define RETAIN 0
#define SENSIFY_MQTT_MESSAGE_SIZE 2400

#define SENSIFY_POLL_RATE 10
#define SENSIFY_POWER_RESTORE_THRESHOLD 20
#define SENSIFY_POWER_FAILURE_THRESHOLD 10

#define SENSIFY_MESSAGE_FAIL_THRESHOLD 4

#define SENSIFY_WATCHDOG_SENSOR_POLL 1000
#define SENSIFY_WATCHDOG_MAIN_CORE 60000

#define SENSIFY_NUMBER_OF_WIFI_PROFILES 3

#define SENSIFY_ENABLE_OUTPUTS 0
#define SENSIFY_TEST_MODE 0

#define SENSIFY_ENCRYPT_CONNSTR 1

#define SENSIFY_SEND_TELEMETRY_INTERVAL 30000
#define SENSIFY_SEND_HEALTH_INTERVAL 900000
#define SENSIFY_HEALTH_SENDS_PER_NTP_REQUEST 96 //24 hours based on 900,000 health interval